"""Display 协议定义 — CLI/Web Display 适配器必须满足的接口

使用 typing.Protocol 实现静态类型检查，无需共同基类继承。
两个实现（cli/display.py 和 web/display.py）隐式满足此协议。
"""
from __future__ import annotations
from typing import Protocol, runtime_checkable, Any


@runtime_checkable
class DisplayProtocol(Protocol):
    """Display 适配器协议

    所有方法都有默认空实现，实现方只需覆盖需要的方法。
    runner/executor 通过此协议调用 display，不再用 hasattr 鸭子类型检查。
    """

    # ── LLM 轮次 ──

    def llm_round_start(self, model: str = "") -> None: ...
    def llm_round_end(self, prompt_tokens: int = 0, completion_tokens: int = 0, model: str = "") -> None: ...

    # ── 思考链 ──

    def thinking_start(self) -> None: ...
    def thinking_chunk(self, text: str) -> None: ...
    def thinking_end(self) -> None: ...

    # ── 文本流 ──

    def text_chunk(self, text: str) -> None: ...
    def text_end(self, full_text: str | None = None) -> str: ...

    # ── 工具调用 ──

    def tool_call_start(self, name: str, args_summary: str, tool_call_id: str = "") -> None: ...
    def tool_result(self, name: str, result: str, elapsed: float | None = None, tool_call_id: str = "") -> None: ...

    # ── 状态通知 ──

    def error(self, text: str) -> None: ...
    def info(self, text: str) -> None: ...
    def teammate_status(self, name: str, status: str) -> None: ...
    def blackboard_update(self, key: str, author: str) -> None: ...
    def inbox_message(self, to: str, from_user: str, count: int) -> None: ...
