"""Display 协议定义 — CLI/Web Display 适配器必须满足的接口

使用 typing.Protocol 实现静态类型检查，无需共同基类继承。
两个实现（cli/display.py 和 web/display.py）隐式满足此协议。
"""
from __future__ import annotations
from typing import Protocol, runtime_checkable, Any

from .runtime_types import DisplayEventPayload, TeamMemberStatus


@runtime_checkable
class DisplayProtocol(Protocol):
    """Display 适配器协议

    核心层只能依赖此协议，不能依赖 CLI/Web 的具体实现、私有字段或传输细节。
    UI/传输层负责把这些协议事件翻译成终端输出、WebSocket 事件或 no-op。
    """

    # ── LLM 轮次 ──

    def llm_round_start(self, model: str = "") -> None: ...
    def llm_round_end(self, prompt_tokens: int = 0, completion_tokens: int = 0, model: str = "") -> None: ...

    # ── 子 Display / 通用事件 ──

    def child(self, *, agent_id: str = "", teammate: str = "", suppress_text: bool | None = None) -> "DisplayProtocol": ...
    def emit(self, event: str, data: DisplayEventPayload | None = None) -> None: ...

    # ── Agent / Workflow 生命周期 ──

    def agent_start(self, agent_type: str, task: str = "", role: str = "", max_turns: int | None = None) -> None: ...
    def workflow_start(self, tasks: list[DisplayEventPayload], total: int) -> None: ...
    def workflow_task_start(self, task_id: str, agent: str, prompt: str) -> None: ...
    def workflow_task_end(self, task_id: str, status: str, result_preview: str | None = None, error: str | None = None) -> None: ...
    def workflow_end(self, elapsed: float, completed: int, failed: int, total: int) -> None: ...

    # ── 思考链 ──

    def thinking_start(self) -> None: ...
    def thinking_chunk(self, text: str) -> None: ...
    def thinking_end(self) -> None: ...
    def thinking_full(self, text: str) -> None: ...

    # ── 文本流 ──

    def text_chunk(self, text: str) -> None: ...
    def text_end(self, full_text: str | None = None) -> str: ...

    # ── 工具调用 ──

    def tool_call_start(self, name: str, args_summary: str, tool_call_id: str = "") -> None: ...
    def tool_result(self, name: str, result: str, elapsed: float | None = None, tool_call_id: str = "") -> None: ...

    # ── 状态通知 ──

    def error(self, text: str) -> None: ...
    def info(self, text: str) -> None: ...
    def teammate_status(self, name: str, status: TeamMemberStatus) -> None: ...
    def blackboard_update(self, key: str, author: str) -> None: ...
    def inbox_message(self, to: str, from_user: str, count: int) -> None: ...
    def plan_event(self, kind: str, **data: Any) -> None: ...
    def todos_updated(self, content: str) -> None: ...
